export const NUM_ROWS = 32;
export const NUM_COLS = 64;
export const START_NODE_X = 10;
export const START_NODE_Y = 10;
export const END_NODE_X = NUM_COLS - 10;
export const END_NODE_Y = NUM_ROWS - 10;
export const NOISE_ZOOM = 0.25;
export const NOISE_OFFSET_X = 10;
export const NOISE_OFFSET_Y = 100;
